# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/susana/software/geant4.10.07.p02/examples/basic

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/susana/software/geant4.10.07.p02/examples/basic/charge

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/susana/software/geant4.10.07.p02/examples/basic/charge/CMakeFiles /home/susana/software/geant4.10.07.p02/examples/basic/charge/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/susana/software/geant4.10.07.p02/examples/basic/charge/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named basic

# Build rule for target.
basic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 basic
.PHONY : basic

# fast build rule for target.
basic/fast:
	$(MAKE) -f CMakeFiles/basic.dir/build.make CMakeFiles/basic.dir/build
.PHONY : basic/fast

#=============================================================================
# Target rules for targets named B1

# Build rule for target.
B1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 B1
.PHONY : B1

# fast build rule for target.
B1/fast:
	$(MAKE) -f B1/CMakeFiles/B1.dir/build.make B1/CMakeFiles/B1.dir/build
.PHONY : B1/fast

#=============================================================================
# Target rules for targets named exampleB1

# Build rule for target.
exampleB1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exampleB1
.PHONY : exampleB1

# fast build rule for target.
exampleB1/fast:
	$(MAKE) -f B1/CMakeFiles/exampleB1.dir/build.make B1/CMakeFiles/exampleB1.dir/build
.PHONY : exampleB1/fast

#=============================================================================
# Target rules for targets named B2

# Build rule for target.
B2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 B2
.PHONY : B2

# fast build rule for target.
B2/fast:
	$(MAKE) -f B2/CMakeFiles/B2.dir/build.make B2/CMakeFiles/B2.dir/build
.PHONY : B2/fast

#=============================================================================
# Target rules for targets named exampleB2a

# Build rule for target.
exampleB2a: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exampleB2a
.PHONY : exampleB2a

# fast build rule for target.
exampleB2a/fast:
	$(MAKE) -f B2/B2a/CMakeFiles/exampleB2a.dir/build.make B2/B2a/CMakeFiles/exampleB2a.dir/build
.PHONY : exampleB2a/fast

#=============================================================================
# Target rules for targets named exampleB2b

# Build rule for target.
exampleB2b: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exampleB2b
.PHONY : exampleB2b

# fast build rule for target.
exampleB2b/fast:
	$(MAKE) -f B2/B2b/CMakeFiles/exampleB2b.dir/build.make B2/B2b/CMakeFiles/exampleB2b.dir/build
.PHONY : exampleB2b/fast

#=============================================================================
# Target rules for targets named B3

# Build rule for target.
B3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 B3
.PHONY : B3

# fast build rule for target.
B3/fast:
	$(MAKE) -f B3/CMakeFiles/B3.dir/build.make B3/CMakeFiles/B3.dir/build
.PHONY : B3/fast

#=============================================================================
# Target rules for targets named B3a

# Build rule for target.
B3a: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 B3a
.PHONY : B3a

# fast build rule for target.
B3a/fast:
	$(MAKE) -f B3/B3a/CMakeFiles/B3a.dir/build.make B3/B3a/CMakeFiles/B3a.dir/build
.PHONY : B3a/fast

#=============================================================================
# Target rules for targets named exampleB3a

# Build rule for target.
exampleB3a: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exampleB3a
.PHONY : exampleB3a

# fast build rule for target.
exampleB3a/fast:
	$(MAKE) -f B3/B3a/CMakeFiles/exampleB3a.dir/build.make B3/B3a/CMakeFiles/exampleB3a.dir/build
.PHONY : exampleB3a/fast

#=============================================================================
# Target rules for targets named B3b

# Build rule for target.
B3b: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 B3b
.PHONY : B3b

# fast build rule for target.
B3b/fast:
	$(MAKE) -f B3/B3b/CMakeFiles/B3b.dir/build.make B3/B3b/CMakeFiles/B3b.dir/build
.PHONY : B3b/fast

#=============================================================================
# Target rules for targets named exampleB3b

# Build rule for target.
exampleB3b: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exampleB3b
.PHONY : exampleB3b

# fast build rule for target.
exampleB3b/fast:
	$(MAKE) -f B3/B3b/CMakeFiles/exampleB3b.dir/build.make B3/B3b/CMakeFiles/exampleB3b.dir/build
.PHONY : exampleB3b/fast

#=============================================================================
# Target rules for targets named B4

# Build rule for target.
B4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 B4
.PHONY : B4

# fast build rule for target.
B4/fast:
	$(MAKE) -f B4/CMakeFiles/B4.dir/build.make B4/CMakeFiles/B4.dir/build
.PHONY : B4/fast

#=============================================================================
# Target rules for targets named exampleB4a

# Build rule for target.
exampleB4a: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exampleB4a
.PHONY : exampleB4a

# fast build rule for target.
exampleB4a/fast:
	$(MAKE) -f B4/B4a/CMakeFiles/exampleB4a.dir/build.make B4/B4a/CMakeFiles/exampleB4a.dir/build
.PHONY : exampleB4a/fast

#=============================================================================
# Target rules for targets named exampleB4b

# Build rule for target.
exampleB4b: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exampleB4b
.PHONY : exampleB4b

# fast build rule for target.
exampleB4b/fast:
	$(MAKE) -f B4/B4b/CMakeFiles/exampleB4b.dir/build.make B4/B4b/CMakeFiles/exampleB4b.dir/build
.PHONY : exampleB4b/fast

#=============================================================================
# Target rules for targets named exampleB4c

# Build rule for target.
exampleB4c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exampleB4c
.PHONY : exampleB4c

# fast build rule for target.
exampleB4c/fast:
	$(MAKE) -f B4/B4c/CMakeFiles/exampleB4c.dir/build.make B4/B4c/CMakeFiles/exampleB4c.dir/build
.PHONY : exampleB4c/fast

#=============================================================================
# Target rules for targets named exampleB4d

# Build rule for target.
exampleB4d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exampleB4d
.PHONY : exampleB4d

# fast build rule for target.
exampleB4d/fast:
	$(MAKE) -f B4/B4d/CMakeFiles/exampleB4d.dir/build.make B4/B4d/CMakeFiles/exampleB4d.dir/build
.PHONY : exampleB4d/fast

#=============================================================================
# Target rules for targets named B5

# Build rule for target.
B5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 B5
.PHONY : B5

# fast build rule for target.
B5/fast:
	$(MAKE) -f B5/CMakeFiles/B5.dir/build.make B5/CMakeFiles/B5.dir/build
.PHONY : B5/fast

#=============================================================================
# Target rules for targets named exampleB5

# Build rule for target.
exampleB5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exampleB5
.PHONY : exampleB5

# fast build rule for target.
exampleB5/fast:
	$(MAKE) -f B5/CMakeFiles/exampleB5.dir/build.make B5/CMakeFiles/exampleB5.dir/build
.PHONY : exampleB5/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... basic"
	@echo "... B1"
	@echo "... exampleB1"
	@echo "... B2"
	@echo "... exampleB2a"
	@echo "... exampleB2b"
	@echo "... B3"
	@echo "... B3a"
	@echo "... exampleB3a"
	@echo "... B3b"
	@echo "... exampleB3b"
	@echo "... B4"
	@echo "... exampleB4a"
	@echo "... exampleB4b"
	@echo "... exampleB4c"
	@echo "... exampleB4d"
	@echo "... B5"
	@echo "... exampleB5"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

